version: '3.8'

services:
  plantation-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - ../data:/app/data
      - ../outputs:/app/outputs
      # Mount service account if available
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/app/service-account.json:ro
    environment:
      - PYTHONPATH=/app
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    command: python run_pipeline.py
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  parallel-monitor:
    extends:
      service: plantation-monitor
    command: python run_pipeline.py --parallel --workers 4
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G 