version: '3.8'

services:
  plantation-monitor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - ../data:/app/data
      - ../outputs:/app/outputs
      - ~/.config/earthengine:/root/.config/earthengine:ro
    environment:
      - SENTINEL_HUB_CLIENT_ID=${SENTINEL_HUB_CLIENT_ID}
      - SENTINEL_HUB_CLIENT_SECRET=${SENTINEL_HUB_CLIENT_SECRET}
    ports:
      - "8888:8888"
    command: python src/data_visualization.py 